#!/bin/bash

uuid1=`uuidgen`

mkdir -p /tmp/ee252

echo $@ | awk '{ for (i=1;i<=NF;i++)printf "%s\n",$i}' > /tmp/ee252/${uuid1}.txt

uuid2=`uuidgen`

mcm_synth -nofs -gc $@ > /tmp/ee252/${uuid2}.txt


vhdl-gen /tmp/ee252/${uuid1}.txt /tmp/ee252/${uuid2}.txt

rm /tmp/ee252/${uuid2}.txt /tmp/ee252/${uuid1}.txt
